# Generated by Django 3.2.15 on 2023-04-05 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dynef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siret', models.CharField(max_length=14)),
                ('raison_sociale', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TotalEnergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueCalcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateToday', models.DateField()),
                ('result', models.FloatField()),
                ('dynef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energie.dynef')),
                ('total_energie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energie.totalenergie')),
            ],
        ),
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_compteur', models.CharField(max_length=30)),
                ('type_energie', models.CharField(max_length=30)),
                ('consommation', models.FloatField()),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energie.societe')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('historiquecalcul', models.ManyToManyField(to='energie.HistoriqueCalcul')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energie.societe')),
            ],
        ),
    ]
