# Generated by Django 3.2.15 on 2023-04-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energie', '0002_auto_20230416_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='password',
            field=models.TextField(max_length=256),
        ),
    ]
