# Generated by Django 3.2.15 on 2023-04-17 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energie', '0003_alter_compte_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='societe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energie.societe'),
        ),
    ]
