# Generated by Django 3.2.15 on 2023-04-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energie', '0004_alter_compte_societe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='updated_at',
        ),
    ]
