# Generated by Django 3.2.15 on 2023-04-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energie', '0005_auto_20230418_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='societe',
        ),
    ]
