# Generated by Django 3.2.15 on 2023-04-18 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energie', '0006_remove_compte_societe'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='compte',
            table='compte',
        ),
    ]
