# Generated by Django 3.2.15 on 2023-04-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energie', '0007_alter_compte_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dynef',
            new_name='Dyneff',
        ),
        migrations.RenameField(
            model_name='historiquecalcul',
            old_name='dynef',
            new_name='dyneff',
        ),
        migrations.AlterModelTable(
            name='compteur',
            table='Compteur',
        ),
        migrations.AlterModelTable(
            name='dyneff',
            table='Dyneff',
        ),
        migrations.AlterModelTable(
            name='historiquecalcul',
            table='HistoriqueCalcul',
        ),
        migrations.AlterModelTable(
            name='societe',
            table='Societe',
        ),
        migrations.AlterModelTable(
            name='totalenergie',
            table='TotalEnergie',
        ),
    ]
