# Generated by Django 3.2.15 on 2023-04-19 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energie', '0008_auto_20230418_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='historiquecalcul',
        ),
        migrations.AddField(
            model_name='historiquecalcul',
            name='societe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='historique_calcul', to='energie.societe'),
        ),
        migrations.AlterModelTable(
            name='compte',
            table='Compte',
        ),
    ]
